endpoints:
  sensitive: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    admin: 
      enabled: true
  redis:
    host: 192.168.1.101
    port: 6379

dnsupdate:
  enabled: false
  interval: 1000
#  cacheStrategy: redis   #local/redis
  
  
