endpoints:
  sensitive: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    admin: 
      enabled: true
  redis:
    host: 10.42.0.56
    port: 6379

dnsupdate:
  enabled: true
  interval: 60000
#  cacheStrategy: redis   #local/redis
  
  
