endpoints:
  sensitive: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    admin: 
      enabled: true
#  redis:
#    host: 10.42.0.56
#    port: 6379

dnsupdate:
  enabled: true
  interval: ${CHECK_INTERVAL:60000}

dnspod:
  login_token: ${LOGIN_TOKEN}
  domain: ${DOMAIN}
  sub_domain: ${SUB_DOMAIN}
  record_line_id: ${RECORD_LINE_ID:0}

cacheStrategy: local   #local/redis

